[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"

[tool.poetry]
packages = [
  { include = "brain_games" },
]

name = "startitin36_brain_games"
version = "0.1.0"
description = ""
authors = ["Leto_RUS <hahmatnur@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
